### PR TITLE
Added reading from stdin and writing to stdout

### PR DESCRIPTION
**Pull request by dustinsmith1024**
I added in reading and writing to stdin/stdout just to allow us to have more flexibility via the command line.

### CODE REVIEW

**Comment by ded** [comment]
right on. I'll test it out in a branch

**Comment by dustinsmith1024** [comment]
had a chance to test it yet?

**Comment by ded** [comment]
hi @dustinsmith1024 sorry i haven't had time recently. i'll give this a whirl now

**Comment by ded** [comment]
great work! thanks

**Pull request merged**
